{
    'name': 'Solvera OJT Kedua',
    'summary': 'Minimum functional module skeleton for Solvera OJT management.',
    'version': '18.0.1.0.0',
    'author': 'Solvera',
    'website': 'https://www.solvera.id',
    'category': 'Human Resources/OJT',
    'license': 'OPL-1',
    'application': True,
    'icon': 'static/description/icon.png',
    'depends': [
        'hr_recruitment',
        'event',
        'website_slides',
        'survey',
        'portal',
        'website',
        'mail',
    ],
    'data': [
        'security/ojt_security.xml',
        'security/ir.model.access.csv',
        'data/ojt_batch_sequence.xml',
        'data/hr_recruitment_stage_data.xml',
        'views/ojt_batch_views.xml',
        'views/hr_applicant_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'auto_install': False,
}
